// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ydwhibxiucctgftqpsnr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inlkd2hpYnhpdWNjdGdmdHFwc25yIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgzNzIxMzEsImV4cCI6MjA2Mzk0ODEzMX0.efGVKrg3QRzmcs3SvnRHv_x6XPzsnILzANwwN8bQwoE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);